
//OK -read
GET http://localhost:3000/api/dogs
###


//OK -create (separate header from body with a blank line between)
POST   http://localhost:3000/api/dogs HTTP/1.1 
content-type: application/json

{
    "name": "vov",
    "born": 2020,
    "breed": "hund"
}
###


//OK -update/replace (separate header from body with a blank line between)
PUT http://localhost:3000/api/dogs/1 HTTP/1.1 
content-type: application/json

{
    "name": "vov",
    "born": 2020,
    "breed": "hund"
}
###


//OK -delete
DELETE http://localhost:3000/api/dogs/1

