
//OK -read
GET http://localhost:3000/api/dogs

###

//json for body ??? -create
POST   http://localhost:3000/api/dogs
//json for body ???
{
    "name": "vov",
    "born": "2020",
    "breed": "hund"
}

###

//json for body ??? -update/replace
PUT http://localhost:3000/api/dogs/1

###


//OK -delete
DELETE http://localhost:3000/api/dogs/1

